version: "3.8"

services:
  core:
    user: root

    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
        - ../:/home/Challenger/
    ports:
        - 8000:8000
    restart: unless-stopped
